name: facil_tenant
description: A new Flutter project.

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
# dependency image_picker: ^0.5.0+9
version: 1.0.2+5

environment:
  sdk: ">=2.2.2 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^0.1.2
  dio: ^4.0.0
  intl: ^0.17.0
  overlay_support: ^1.2.0
  path_provider: ^2.0.1
  provider: ^5.0.0
  get_it: ^6.0.0
  json_annotation: ^4.0.1
  datetime_picker_formfield: ^2.0.0
  dropdownfield: ^1.0.3
  badges: ^1.2.0
  flutter_picker: ^2.0.1
  image_picker: ^0.7.4
  file_picker: ^3.0.1
  url_launcher: ^6.0.3
  crypto: ^3.0.1
  flutter_pdfview: ^1.1.0
  image: ^3.0.2
  fluttertoast: ^8.0.3
  cached_network_image: ^3.0.0
  flutter_inappwebview: ^5.3.1+1
  shared_preferences: ^2.0.5

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_launcher_icons: ^0.9.0
  build_runner: ^1.12.2
  json_serializable: ^4.1.0

flutter_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/icon/icon.png"

flutter:
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
    - assets/img/

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware.

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  fonts:
    - family: Ubuntu
      fonts:
        - asset: assets/fonts/Ubuntu/Ubuntu-Regular.ttf
        - asset: assets/fonts/Ubuntu/Ubuntu-Italic.ttf
        - asset: assets/fonts/Ubuntu/Ubuntu-Bold.ttf
        - asset: assets/fonts/Ubuntu/Ubuntu-Light.ttf
        - asset: assets/fonts/Ubuntu/Ubuntu-Medium.ttf
          style: italic
    - family: Octin
      fonts:
        - asset: assets/fonts/octin_stencil_rg.otf
          weight: 800
    - family: Opensans
      fonts:
        - asset: assets/fonts/OpenSans-Regular.ttf
        - asset: assets/fonts/OpenSans-Bold.ttf
        - asset: assets/fonts/OpenSans-Italic.ttf
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
