const config = {
  //"baseUrl": "http://api.facilng.net/estate/web/",
  "baseUrl": "http://192.168.8.100/estate/web/",
  "user": "user/",
  "login": "login/",
  "announcements": "announcements/",
  "message": "message/",
  "visit": "propertyaccess/",
  "create": "create/",
  "view": "view/",
  "register": "registration/",
  "update": "update/",
  "request": "request/",
  "requestType": "requesttype/",
};